AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3]  # as per VGG model
BATCH_SIZE: 16             # can increase based on machine hardware
INCLUDE_TOP: False         # using pretrained model (training only custom layer)
EPOCHS: 1
CLASSES: 2
WEIGHTS: imagenet
LEARNING_RATE: 0.01